#!/usr/bin/env python3
"""
Airtable Setup Script for TTR Signal Detection System

Automatically creates all required fields in the existing Airtable table
using the Airtable Metadata API. The table must already exist — this script
builds out the complete field schema.

Usage:
    python3 airtable_setup.py                        # Run full setup
    python3 airtable_setup.py --dry-run              # Preview without making changes
    python3 airtable_setup.py --list-fields          # Print field list (no credentials needed)
    python3 airtable_setup.py --json                 # Export field structure as JSON
    python3 airtable_setup.py --table "My Table"     # Target a specific table name

Requirements:
    pip install requests python-dotenv

Credentials (add to .env file):
    AIRTABLE_API_TOKEN=your_personal_access_token
    AIRTABLE_BASE_ID=your_base_id
"""

import json
import os
import sys
import time
import argparse
import requests
from pathlib import Path
from typing import List, Dict, Any, Optional

# ── Load .env ────────────────────────────────────────────────────────────────
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # Fallback: manually parse .env if python-dotenv is not installed yet
    env_path = Path(__file__).parent / '.env'
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, _, value = line.partition('=')
                    os.environ.setdefault(key.strip(), value.strip())


# ── Field Definitions ─────────────────────────────────────────────────────────

FIELD_DEFINITIONS: List[Dict[str, Any]] = [
    # ── Identity ──────────────────────────────────────────────────────────────
    {
        "name": "Signal ID",
        "type": "singleLineText",
        "description": "Unique identifier to prevent duplicates (auto-generated by the pipeline)"
    },
    {
        "name": "Run ID",
        "type": "singleLineText",
        "description": "Identifies which scraping run found this signal (format: run_YYYYMMDD_HHMMSS_uuid)"
    },

    # ── Company ───────────────────────────────────────────────────────────────
    {
        "name": "Company Name",
        "type": "singleLineText",
        "description": "Name of the company extracted from the signal article"
    },
    {
        "name": "Website",
        "type": "url",
        "description": "Company website URL (if available)"
    },

    # ── Signal Classification ─────────────────────────────────────────────────
    {
        "name": "Signal Type",
        "type": "singleSelect",
        "options": [
            {"name": "funding_announcement", "color": "greenBright"},
            {"name": "product_launch",       "color": "blueBright"},
            {"name": "hiring_spree",         "color": "purpleBright"}
        ],
        "description": "Type of signal detected by Tier 1 pattern matcher"
    },
    {
        "name": "ICP Vertical",
        "type": "singleSelect",
        "options": [
            {"name": "ai_ml",           "color": "greenBright"},
            {"name": "blockchain_web3", "color": "orangeBright"},
            {"name": "fintech",         "color": "blueBright"},
            {"name": "not_icp",         "color": "redBright"}
        ],
        "description": "Ideal Customer Profile vertical classification from Tier 2 validator"
    },
    {
        "name": "Funding Stage",
        "type": "singleSelect",
        "options": [
            {"name": "pre_seed", "color": "yellowBright"},
            {"name": "seed",     "color": "orangeBright"},
            {"name": "series_a", "color": "greenBright"},
            {"name": "unknown",  "color": "grayBright"}
        ],
        "description": "Company funding stage detected from article context"
    },
    {
        "name": "Funding Amount",
        "type": "currency",
        "options": {
            "symbol": "$",
            "precision": 0
        },
        "description": "Funding amount in USD (extracted from article text)"
    },

    # ── Confidence Scores ─────────────────────────────────────────────────────
    {
        "name": "Tier 1 Confidence",
        "type": "number",
        "options": {
            "precision": 2
        },
        "description": "Original pattern-matching confidence score (0.0 – 1.0)"
    },
    {
        "name": "Tier 2 Confidence",
        "type": "number",
        "options": {
            "precision": 2
        },
        "description": "Enhanced confidence after ICP + stage validation (0.0 – 1.0)"
    },
    {
        "name": "Context Validated",
        "type": "checkbox",
        "options": {
            "icon": "check",
            "color": "greenBright"
        },
        "description": "True if the signal passed Tier 2 context validation"
    },
    {
        "name": "Signal Rationale",
        "type": "multilineText",
        "description": "Human-readable explanation of why this signal was classified (generated by pipeline)"
    },

    # ── Source Article ────────────────────────────────────────────────────────
    {
        "name": "Article Title",
        "type": "multilineText",
        "description": "Title of the source article"
    },
    {
        "name": "Source URL",
        "type": "url",
        "description": "Direct URL to the source article"
    },
    {
        "name": "Article Date",
        "type": "date",
        "options": {
            "dateFormat": {
                "name": "local",
                "format": "l"
            }
        },
        "description": "Date the article was published"
    },
    {
        "name": "Date Detected",
        "type": "dateTime",
        "options": {
            "dateFormat": {
                "name": "local",
                "format": "l"
            },
            "timeFormat": {
                "name": "24hour",
                "format": "HH:mm"
            },
            "timeZone": "utc"
        },
        "description": "Timestamp when the signal was detected by the pipeline (UTC)"
    },

    # ── Context / Keywords ────────────────────────────────────────────────────
    {
        "name": "Context Preview",
        "type": "multilineText",
        "description": "Excerpt from the article surrounding the matched signal keywords (up to 500 chars)"
    },
    {
        "name": "Matched Keywords",
        "type": "multilineText",
        "description": "Comma-separated list of Tier 1 keywords that triggered detection"
    },
    {
        "name": "Vertical Keywords",
        "type": "multilineText",
        "description": "ICP vertical keywords found in surrounding context"
    },
    {
        "name": "Stage Keywords",
        "type": "multilineText",
        "description": "Funding stage keywords found in surrounding context"
    },

    # ── Review Workflow ───────────────────────────────────────────────────────
    {
        "name": "Review Status",
        "type": "singleSelect",
        "options": [
            {"name": "Pending",        "color": "yellowBright"},
            {"name": "Approved",       "color": "greenBright"},
            {"name": "Rejected",       "color": "redBright"},
            {"name": "Needs Research", "color": "orangeBright"},
            {"name": "Sent to Attio",  "color": "purpleBright"}
        ],
        "description": "Manual review status — set to Approved then check Send to Attio to sync"
    },
    {
        "name": "Review Notes",
        "type": "multilineText",
        "description": "Notes from the manual review process"
    },

    # ── Attio CRM Sync ────────────────────────────────────────────────────────
    {
        "name": "Send to Attio",
        "type": "checkbox",
        "options": {
            "icon": "check",
            "color": "blueBright"
        },
        "description": "Check this to queue the record for Attio CRM sync"
    },
    {
        "name": "Attio Sync Status",
        "type": "singleSelect",
        "options": [
            {"name": "Not Synced", "color": "grayBright"},
            {"name": "Pending",    "color": "yellowBright"},
            {"name": "Synced",     "color": "greenBright"},
            {"name": "Failed",     "color": "redBright"}
        ],
        "description": "Current status of Attio CRM synchronization"
    },
    {
        "name": "Attio Sync Date",
        "type": "dateTime",
        "options": {
            "dateFormat": {
                "name": "local",
                "format": "l"
            },
            "timeFormat": {
                "name": "24hour",
                "format": "HH:mm"
            },
            "timeZone": "utc"
        },
        "description": "Timestamp when this record was last synced to Attio (UTC)"
    }
]


# ── Airtable API Client ───────────────────────────────────────────────────────

class AirtableSetup:
    """
    Connects to the Airtable Metadata API and creates the full field schema
    for the Marketing Partnership Signals table.
    """

    META_BASE_URL = "https://api.airtable.com/v0/meta"

    def __init__(self):
        self.api_token = os.environ.get('AIRTABLE_API_TOKEN', '').strip()
        self.base_id   = os.environ.get('AIRTABLE_BASE_ID', '').strip()

        if not self.api_token or self.api_token in ('your_token_here', ''):
            self._missing_credentials()

        if not self.base_id or self.base_id in ('your_base_id_here', ''):
            self._missing_credentials()

        self.headers = {
            'Authorization': f'Bearer {self.api_token}',
            'Content-Type': 'application/json'
        }

    # ── Credential helper ──────────────────────────────────────────────────────

    @staticmethod
    def _missing_credentials():
        print("\n❌  Missing Airtable credentials.\n")
        print("    Add the following to your .env file:\n")
        print("        AIRTABLE_API_TOKEN=pat_xxxxxxxxxx")
        print("        AIRTABLE_BASE_ID=appXXXXXXXXXXXXXX\n")
        print("    Get your token at:  https://airtable.com/create/tokens")
        print("    Find your Base ID:  open the base → Help → API docs → base ID in the URL\n")
        sys.exit(1)

    # ── Table Discovery ────────────────────────────────────────────────────────

    def get_tables(self) -> List[Dict]:
        """Fetch all tables in the configured base."""
        url = f"{self.META_BASE_URL}/bases/{self.base_id}/tables"
        response = requests.get(url, headers=self.headers)

        if response.status_code == 401:
            print("❌  Authentication failed. Check your AIRTABLE_API_TOKEN.")
            sys.exit(1)
        if response.status_code == 404:
            print(f"❌  Base '{self.base_id}' not found. Check your AIRTABLE_BASE_ID.")
            sys.exit(1)
        if response.status_code != 200:
            print(f"❌  Failed to fetch tables: {response.status_code} — {response.text}")
            sys.exit(1)

        return response.json().get('tables', [])

    def find_table(self, table_name: str) -> Optional[Dict]:
        """Find a table by exact name."""
        for table in self.get_tables():
            if table.get('name') == table_name:
                return table
        return None

    @staticmethod
    def get_existing_field_names(table: Dict) -> List[str]:
        """Return a list of field names that already exist in the table."""
        return [field['name'] for field in table.get('fields', [])]

    # ── Field Creation ────────────────────────────────────────────────────────

    def _build_payload(self, field_def: Dict) -> Dict:
        """Convert our field definition into an Airtable API-compatible payload."""
        field_type = field_def['type']

        payload: Dict[str, Any] = {
            'name': field_def['name'],
            'type': field_type,
        }

        if 'description' in field_def:
            payload['description'] = field_def['description']

        # singleSelect → wrap choices in options
        if field_type == 'singleSelect':
            payload['options'] = {
                'choices': field_def.get('options', [])
            }

        # currency, number, date, dateTime, checkbox → pass options as-is
        elif 'options' in field_def:
            payload['options'] = field_def['options']

        return payload

    def create_field(self, table_id: str, field_def: Dict, dry_run: bool = False) -> bool:
        """
        Create a single field via the Airtable Metadata API.

        Returns True on success or skip, False on error.
        """
        field_name = field_def['name']

        if dry_run:
            print(f"   [DRY RUN] Would create: {field_name} ({field_def['type']})")
            return True

        url = f"{self.META_BASE_URL}/bases/{self.base_id}/tables/{table_id}/fields"
        payload = self._build_payload(field_def)

        response = requests.post(url, headers=self.headers, json=payload)

        # Respect Airtable rate limits (5 req/sec for metadata API)
        time.sleep(0.25)

        if response.status_code in (200, 201):
            print(f"   ✅  Created : {field_name}  ({field_def['type']})")
            return True

        error_data = response.json() if response.text else {}
        error_msg  = error_data.get('error', {}).get('message', response.text)

        if response.status_code == 422:
            # Typically "field already exists" or invalid config
            print(f"   ⚠️   Skipped : {field_name} — {error_msg}")
            return True   # Don't count as failure

        print(f"   ❌  Failed  : {field_name} — {response.status_code} {error_msg}")
        return False

    # ── Main Setup Flow ───────────────────────────────────────────────────────

    def setup(self, table_name: str = "Marketing Partnership Signals", dry_run: bool = False):
        """
        Run the full setup: find the table, diff existing fields, create missing ones.
        """
        print("\n🎯  TTR Signal Detection — Airtable Field Setup")
        print("=" * 60)

        if dry_run:
            print("⚠️   DRY RUN MODE — no changes will be made\n")

        # Find table
        print(f"🔍  Looking for table: '{table_name}' in base {self.base_id}...")
        table = self.find_table(table_name)

        if not table:
            print(f"\n❌  Table '{table_name}' not found.")
            print("\n📋  Available tables in this base:")
            for t in self.get_tables():
                print(f"    • {t['name']}  (ID: {t['id']})")
            print(f"\n    Use --table \"<exact name>\" to target a different table.")
            sys.exit(1)

        table_id = table['id']
        print(f"✅  Found table: '{table_name}'  (ID: {table_id})\n")

        # Diff existing vs required
        existing = self.get_existing_field_names(table)
        to_create = [f for f in FIELD_DEFINITIONS if f['name'] not in existing]
        to_skip   = [f for f in FIELD_DEFINITIONS if f['name'] in existing]

        print(f"📊  Field summary:")
        print(f"    • Total fields required : {len(FIELD_DEFINITIONS)}")
        print(f"    • Already exist         : {len(to_skip)}")
        print(f"    • Will be created       : {len(to_create)}")

        if to_skip:
            print(f"\n⏭️   Skipping existing fields:")
            for f in to_skip:
                print(f"    • {f['name']}")

        if not to_create:
            print("\n✅  All fields already exist — nothing to do!\n")
            return

        print(f"\n🔨  Creating {len(to_create)} fields...\n")

        success_count = 0
        fail_count    = 0

        for field_def in to_create:
            ok = self.create_field(table_id, field_def, dry_run)
            if ok:
                success_count += 1
            else:
                fail_count += 1

        # ── Summary ──────────────────────────────────────────────────────────
        print(f"\n{'='*60}")
        print(f"📊  Results:")
        print(f"    • Created successfully : {success_count}")
        print(f"    • Failed               : {fail_count}")
        print(f"    • Already existed      : {len(to_skip)}")

        if fail_count == 0:
            print(f"\n🎉  Setup complete! All fields are ready in '{table_name}'.")
            print(f"\n📍  Next steps:")
            print(f"    1. Run: python3 run_signal_detection.py --days=1")
            print(f"    2. Check that signals appear in your Airtable table")
            print(f"    3. Review signals and set 'Review Status' → 'Approved'")
            print(f"    4. Check 'Send to Attio' to queue records for CRM sync")
        else:
            print(f"\n⚠️   {fail_count} field(s) failed. Review errors above and re-run the script.")
            print(f"    The script is safe to re-run — existing fields are never overwritten.\n")


# ── Backwards-compatible helpers (used by other modules) ──────────────────────

def get_airtable_field_structure() -> List[Dict]:
    """Return the complete field definition list (no credentials required)."""
    return FIELD_DEFINITIONS


def get_sample_record() -> Dict:
    """Return a sample record showing the expected data format."""
    return {
        "Signal ID":        "sig_a1b2c3d4e5f6",
        "Run ID":           "run_20260407_083045_abc12345",
        "Company Name":     "AI Analytics Corp",
        "Website":          "https://aianalytic.com",
        "Signal Type":      "funding_announcement",
        "ICP Vertical":     "ai_ml",
        "Funding Stage":    "seed",
        "Funding Amount":   2300000,
        "Tier 1 Confidence": 0.92,
        "Tier 2 Confidence": 0.89,
        "Context Validated": True,
        "Signal Rationale":  "AI/ML company, Seed $2.3M funding announcement.",
        "Article Title":    "AI Analytics Corp Raises $2.3M Seed Round",
        "Source URL":       "https://techcrunch.com/ai-analytics-funding",
        "Article Date":     "2026-04-06",
        "Date Detected":    "2026-04-07T08:30:45.123Z",
        "Context Preview":  "AI Analytics Corp announced today it has raised $2.3M...",
        "Matched Keywords": "raised, seed round, funding, artificial intelligence",
        "Vertical Keywords": "AI, artificial intelligence, machine learning",
        "Stage Keywords":    "seed round, seed funding",
        "Review Status":    "Pending",
        "Review Notes":     "",
        "Send to Attio":    False,
        "Attio Sync Status": "Not Synced",
        "Attio Sync Date":  None
    }


def print_field_structure():
    """Print the field structure in a human-readable format."""
    print("🎯  TTR Marketing Partnership Signals — Airtable Field Structure")
    print("=" * 70)
    print(f"Total Fields: {len(FIELD_DEFINITIONS)}\n")

    for i, field in enumerate(FIELD_DEFINITIONS, 1):
        print(f"{i:2}. {field['name']}")
        print(f"    Type       : {field['type']}")
        print(f"    Description: {field.get('description', '')}")

        if field['type'] == 'singleSelect' and 'options' in field:
            choices = [opt['name'] for opt in field['options']]
            print(f"    Choices    : {choices}")
        elif field['type'] == 'currency' and 'options' in field:
            print(f"    Currency   : {field['options'].get('symbol', '$')}")
        elif field['type'] == 'number' and 'options' in field:
            print(f"    Precision  : {field['options'].get('precision', 2)} decimal places")
        elif field['type'] in ('date', 'dateTime') and 'options' in field:
            fmt = field['options'].get('dateFormat', {}).get('name', 'local')
            print(f"    Date format: {fmt}")

        print()


# ── Entry Point ───────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description='TTR Airtable Setup — create field schema in an existing table'
    )
    parser.add_argument(
        '--table',
        default='Marketing Partnership Signals',
        help='Exact table name to set up (default: "Marketing Partnership Signals")'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Preview what would be created without making any changes'
    )
    parser.add_argument(
        '--list-fields',
        action='store_true',
        help='Print the full field structure (no credentials required)'
    )
    parser.add_argument(
        '--json',
        action='store_true',
        help='Output field structure as JSON (no credentials required)'
    )

    args = parser.parse_args()

    # ── No-credential modes ───────────────────────────────────────────────────
    if args.list_fields:
        print_field_structure()
        return

    if args.json:
        print(json.dumps(FIELD_DEFINITIONS, indent=2))
        return

    # ── Live API mode ─────────────────────────────────────────────────────────
    setup = AirtableSetup()
    setup.setup(table_name=args.table, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
